{{- if .Values.nexus.docker.enabled -}}
{{ $root := . }}
{{- range $registry := .Values.nexus.docker.registries }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nexus.fullname" $root | trunc 35 }}-dkr-{{ $registry.repo | trunc 20 }}
  namespace: {{ default $root.Release.Namespace $root.Values.namespaces.nexusNs.name | quote }}
  labels:
    {{- include "nexus.labels" $root | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/balance: "source"
    haproxy.router.openshift.io/timeout: "600s"
    haproxy.router.openshift.io/timeout-tunnel: "3600s"
    haproxy.router.openshift.io/disable_cookies: "true"
    haproxy.router.openshift.io/hsts_header: "max-age=31536000;includeSubDomains"
spec:
  {{- if $root.Values.wildcardTls.enabled }}
  tls:
    - hosts:
        - {{ $registry.host }}.nexus-t01.sunrise.ch
      secretName: {{ $root.Values.wildcardTls.existingSecretName }}
  {{- end }}
  rules:
    - host: {{ $registry.host }}.nexus-t01.sunrise.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nexus.fullname" $root | trunc 54 }}-docker
                port:
                  number: {{ $registry.port }}
{{- end }}
{{- end }}
