{{- if and .Values.wildcardTls.enabled .Values.wildcardTls.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.wildcardTls.existingSecretName }}
  namespace: {{ default .Release.Namespace .Values.namespaces.nexusNs.name | quote }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    sealedsecrets.bitnami.com/cluster-wide: "false"
spec:
  encryptedData:
    tls.crt: {{ .Values.wildcardTls.sealedSecret.encryptedCert | quote }}
    tls.key: {{ .Values.wildcardTls.sealedSecret.encryptedKey | quote }}
    {{- if .Values.wildcardTls.sealedSecret.encryptedCaCert }}
    ca.crt: {{ .Values.wildcardTls.sealedSecret.encryptedCaCert | quote }}
    {{- end }}
  template:
    type: kubernetes.io/tls
    metadata:
      name: {{ .Values.wildcardTls.existingSecretName }}
      namespace: {{ default .Release.Namespace .Values.namespaces.nexusNs.name | quote }}
      labels:
        {{- include "nexus.labels" . | nindent 8 }}
{{- end }}
